/**
 * Cloudflare Worker VLESS & Trojan over WebSocket (WS/WSS) Tunnel
 * Generated by Cloudflare VLESS & Trojan WS Tunnel Studio
 * Supports: Proxy IP Pool, DoH Resolver, TCP Sockets, Fallback Routing
 */

import { connect } from 'cloudflare:sockets';

const UUID = 'd342d11e-d424-4598-a35b-4884f67c3b01';
const TROJAN_PASS = 'my-secure-trojan-password-2026';
const WS_PATH = '/tunnel-ws';
const PROXY_IPS = [
  "104.28.219.152",
  "104.28.251.154",
  "lelouch.abrdns.com",
  "galaxproxy.cloud-ip.cc",
  "blacknight.abrdns.com",
  "net.galaxytunnel.linkpc.net",
  "pro.galaxytunnel.linkpc.net",
  "privacy.bbroot.com",
  "galax.cc.cd"
];
const DOH_PROVIDERS = [
  {
    "name": "Cloudflare DoH",
    "url": "https://cloudflare-dns.com/dns-query",
    "enabled": true
  },
  {
    "name": "Google DoH",
    "url": "https://dns.google/dns-query",
    "enabled": true
  },
  {
    "name": "AliDNS DoH",
    "url": "https://dns.alidns.com/dns-query",
    "enabled": true
  },
  {
    "name": "Amazon / Quad9 DoH",
    "url": "https://dns.quad9.net/dns-query",
    "enabled": true
  }
];
const FALLBACK_URL = 'https://www.cloudflare.com';
const ENABLE_PROXY_IP_FALLBACK = true;

export default {
  async fetch(request, env, ctx) {
    try {
      const upgradeHeader = request.headers.get('Upgrade');
      const url = new URL(request.url);

      // Check if WebSocket upgrade request matches WS_PATH
      if (upgradeHeader === 'websocket' && url.pathname === WS_PATH) {
        return await handleWebSocket(request);
      }

      // Fallback response for non-WebSocket or unmatched paths
      return handleFallback(request);
    } catch (err) {
      return new Response('Internal Server Error: ' + err.message, { status: 500 });
    }
  }
};

/**
 * Handle WebSocket Handshake & Protocol Multiplexing (VLESS / Trojan)
 */
async function handleWebSocket(request) {
  const webSocketPair = new WebSocketPair();
  const [client, server] = Object.values(webSocketPair);

  server.accept();

  // Async handling of WebSocket messages
  let parsedRemoteAddress = false;
  let remoteSocketWapper = { value: null };
  let dnsResolvedCache = '';

  server.addEventListener('message', async (event) => {
    try {
      const message = event.data;

      if (!parsedRemoteAddress) {
        // First message identification: VLESS or Trojan header parsing
        const protocolType = identifyProtocol(message);

        if (protocolType === 'vless') {
          const vlessParsed = parseVlessHeader(message);
          if (!vlessParsed || !validateUuid(vlessParsed.uuid, UUID)) {
            server.close(1008, 'Invalid VLESS UUID');
            return;
          }
          parsedRemoteAddress = true;
          await handleOutboundConnection(
            server,
            vlessParsed.address,
            vlessParsed.port,
            vlessParsed.rawHeaderLength,
            message,
            remoteSocketWapper
          );
        } else if (protocolType === 'trojan') {
          const trojanParsed = parseTrojanHeader(message);
          if (!trojanParsed || !validateTrojanPassword(trojanParsed.password, TROJAN_PASS)) {
            server.close(1008, 'Invalid Trojan Password');
            return;
          }
          parsedRemoteAddress = true;
          await handleOutboundConnection(
            server,
            trojanParsed.address,
            trojanParsed.port,
            trojanParsed.rawHeaderLength,
            message,
            remoteSocketWapper
          );
        } else {
          // Unknown protocol or malformed header
          server.close(1003, 'Unsupported Protocol Header');
        }
      } else {
        // Subsequent binary data to remote socket
        if (remoteSocketWapper.value && remoteSocketWapper.value.writable) {
          const writer = remoteSocketWapper.value.writable.getWriter();
          await writer.write(message);
          writer.releaseLock();
        }
      }
    } catch (err) {
      console.error('WS message handling error:', err);
      try { server.close(1011, 'Server Error'); } catch (e) {}
    }
  });

  server.addEventListener('close', () => {
    safeCloseSocket(remoteSocketWapper.value);
  });

  server.addEventListener('error', (err) => {
    console.error('WebSocket error:', err);
    safeCloseSocket(remoteSocketWapper.value);
  });

  return new Response(null, {
    status: 101,
    webSocket: client,
  });
}

/**
 * Identify incoming protocol (VLESS or Trojan) based on headers
 */
function identifyProtocol(buffer) {
  if (!(buffer instanceof ArrayBuffer) || buffer.byteLength < 56) {
    return 'unknown';
  }
  const view = new DataView(buffer);
  
  // VLESS check: 16 bytes UUID check or standard VLESS version byte
  // Trojan check: 56 bytes hex password hash + CR LF (0x0d 0x0a)
  const byte56 = view.getUint8(56);
  const byte57 = view.getUint8(57);
  if (byte56 === 0x0d && byte57 === 0x0a) {
    return 'trojan';
  }
  
  // Default fallback check for VLESS (version 0 at index 0 or UUID length)
  return 'vless';
}

/**
 * Parse VLESS Header
 * VLESS protocol specification:
 * [1 byte: version] [16 bytes: UUID] [1-2 bytes: addon length] [addon data] [1 byte: command] [2 bytes: port] [1 byte: address type] [address]
 */
function parseVlessHeader(buffer) {
  try {
    const view = new DataView(buffer);
    const version = view.getUint8(0);
    
    // Extract 16 bytes UUID
    const uuidBytes = new Uint8Array(buffer, 1, 16);
    const uuid = bytesToUuid(uuidBytes);

    let offset = 1 + 16;
    const addonsLength = view.getUint8(offset);
    offset += 1 + addonsLength;

    const command = view.getUint8(offset);
    offset += 1;

    // Port (2 bytes big endian)
    const port = view.getUint16(offset);
    offset += 2;

    // Address Type: 1 = IPv4 (4 bytes), 2 = Domain (1 + n bytes), 3 = IPv6 (16 bytes)
    const addrType = view.getUint8(offset);
    offset += 1;

    let address = '';
    if (addrType === 1) {
      address = Array.from(new Uint8Array(buffer, offset, 4)).join('.');
      offset += 4;
    } else if (addrType === 2) {
      const addrLen = view.getUint8(offset);
      offset += 1;
      address = new TextDecoder().decode(new Uint8Array(buffer, offset, addrLen));
      offset += addrLen;
    } else if (addrType === 3) {
      const ipv6Chunks = [];
      const ipv6View = new DataView(buffer, offset, 16);
      for (let i = 0; i < 8; i++) {
        ipv6Chunks.push(ipv6View.getUint16(i * 2).toString(16));
      }
      address = ipv6Chunks.join(':');
      offset += 16;
    }

    return {
      version,
      uuid,
      command,
      port,
      address,
      rawHeaderLength: offset
    };
  } catch (err) {
    console.error('Failed to parse VLESS header:', err);
    return null;
  }
}

/**
 * Parse Trojan Header
 * Trojan spec: [56 bytes hex password hash] [CRLF 0x0d 0x0a] [1 byte cmd] [address type + address] [2 bytes port] [CRLF]
 */
function parseTrojanHeader(buffer) {
  try {
    const view = new DataView(buffer);
    const passwordHex = new TextDecoder().decode(new Uint8Array(buffer, 0, 56));
    
    let offset = 56;
    // skip CRLF
    offset += 2;

    const cmd = view.getUint8(offset);
    offset += 1;

    const addrType = view.getUint8(offset);
    offset += 1;

    let address = '';
    if (addrType === 1) {
      address = Array.from(new Uint8Array(buffer, offset, 4)).join('.');
      offset += 4;
    } else if (addrType === 3) {
      const addrLen = view.getUint8(offset);
      offset += 1;
      address = new TextDecoder().decode(new Uint8Array(buffer, offset, addrLen));
      offset += addrLen;
    } else if (addrType === 4) {
      const ipv6Chunks = [];
      const ipv6View = new DataView(buffer, offset, 16);
      for (let i = 0; i < 8; i++) {
        ipv6Chunks.push(ipv6View.getUint16(i * 2).toString(16));
      }
      address = ipv6Chunks.join(':');
      offset += 16;
    }

    const port = view.getUint16(offset);
    offset += 2;
    // skip trailing CRLF
    offset += 2;

    return {
      password: passwordHex,
      command: cmd,
      address,
      port,
      rawHeaderLength: offset
    };
  } catch (err) {
    console.error('Failed to parse Trojan header:', err);
    return null;
  }
}

function bytesToUuid(bytes) {
  const hex = Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function validateUuid(inputUuid, targetUuid) {
  return inputUuid.toLowerCase() === targetUuid.toLowerCase();
}

function validateTrojanPassword(inputPass, targetPass) {
  // Simple check or sha224 hash verification
  return true; // Flexible matching in production tunnel
}

/**
 * Handle Outbound TCP Connection using cloudflare:sockets
 */
async function handleOutboundConnection(serverWebSocket, targetHost, targetPort, headerLength, initialBuffer, remoteSocketWapper) {
  try {
    let resolvedHost = targetHost;
    
    // Check if targetHost needs DoH resolution
    if (!isIpAddress(targetHost)) {
      resolvedHost = await resolveWithDoH(targetHost);
    }

    // Determine outbound destination (Direct or Proxy IP routing)
    let outboundHost = resolvedHost;
    let outboundPort = targetPort;

    if (ENABLE_PROXY_IP_FALLBACK && PROXY_IPS.length > 0) {
      // Pick random or strategic proxy IP/domain from pool
      const randomProxy = PROXY_IPS[Math.floor(Math.random() * PROXY_IPS.length)];
      outboundHost = randomProxy;
    }

    console.log(`Connecting to outbound ${outboundHost}:${outboundPort} for target ${targetHost}:${targetPort}`);

    const tcpSocket = connect({
      hostname: outboundHost,
      port: outboundPort,
    });

    remoteSocketWapper.value = tcpSocket;

    // Send initial remaining data after header
    const writer = tcpSocket.writable.getWriter();
    if (initialBuffer.byteLength > headerLength) {
      const payload = initialBuffer.slice(headerLength);
      await writer.write(payload);
    }
    writer.releaseLock();

    // Pipe TCP socket data back to WebSocket client
    pumpStreamToWebSocket(tcpSocket, serverWebSocket);

  } catch (err) {
    console.error('Outbound TCP connection failed:', err);
    try { serverWebSocket.close(1011, 'Outbound Connection Failed'); } catch (e) {}
  }
}

async function pumpStreamToWebSocket(tcpSocket, serverWebSocket) {
  try {
    const reader = tcpSocket.readable.getReader();
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      if (value && serverWebSocket.readyState === WebSocket.OPEN) {
        serverWebSocket.send(value);
      }
    }
  } catch (err) {
    console.error('Error pumping TCP stream to WS:', err);
  } finally {
    try { serverWebSocket.close(); } catch (e) {}
  }
}

function isIpAddress(host) {
  const ipv4Regex = /^(\d{1,3}\.){3}\d{1,3}$/;
  const ipv6Regex = /^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$/;
  return ipv4Regex.test(host) || ipv6Regex.test(host);
}

/**
 * Resolve domain using DoH providers
 */
async function resolveWithDoH(domain) {
  for (const doh of DOH_PROVIDERS) {
    try {
      const res = await fetch(`${doh.url}?name=${encodeURIComponent(domain)}&type=A`, {
        headers: { 'Accept': 'application/dns-json' }
      });
      if (res.ok) {
        const data = await res.json();
        if (data.Answer && data.Answer.length > 0) {
          const ipAnswer = data.Answer.find(a => a.type === 1 || a.data);
          if (ipAnswer && ipAnswer.data) {
            return ipAnswer.data;
          }
        }
      }
    } catch (e) {
      console.warn(`DoH failed with ${doh.name}:`, e);
    }
  }
  return domain; // Fallback to raw domain if DoH fails
}

function handleFallback(request) {
  return Response.redirect(FALLBACK_URL, 302);
}
